### ISSUE TITLE
how to change default width for mobile view in partialViewSlider ?

### ISSUE THREAD

**Issue by psa1308** [VeeK727/partialViewSlider#1]
default width set for active slider is 70% percentage by default and i want to show 100% width when mobile screen starts any help would be very helpful.

**Comment by psa1308** [comment]
Here is the js code of partialViewSlider:

_Removed partialviewslider.js file's code for better understanding_

**Comment by Whip** [comment]
Hi @psa1308 , you have posted the library file partialviewslider.js. You should only include the file in your project and not make any changes to it. Please read the readme.md for instructions on how to setup the slider in your project.

Then you can use the options to make center slide 100%,  eg: 
```
$('#slider').partialViewSlider({
   width: 100
});
```

**Comment by psa1308** [comment]
thanks it worked
